site_name: tskb
repo_url: https://github.com/tmssd/kb
repo_name: tmssd/kb
edit_uri: edit/main/docs/
theme:
  icon:
      logo: material/book-open-page-variant
      repo: fontawesome/brands/github
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    # - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
plugins:
  - search
  # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
  - awesome-pages
  # https://github.com/apenwarr/mkdocs-exclude
  - git-revision-date:
      enabled_if_env: CI
  - exclude:
      glob:
        - "*+OFFL/*"
  # https://github.com/soulless-viewer/mkdocs-video
  - mkdocs-video:
      css_style:
        width: "24vw"
        height: "15vw"
markdown_extensions:
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      # linenums: true
      # linenums_style: table
      # anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - tables
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
